### ISSUE TITLE
Mostrar o status do mercado

### ISSUE THREAD

**Issue by jacksoncastro** [TheGuardiansOfBrotherhood/CartolaUWP#4]
Como usuário, gostaria de poder ver o status atual do mercado, exibido de maneira intuitiva e elegante

**Comment by jacksoncastro** [comment]
@arlesonsilva conseguiu ver essa atividade?

**Comment by arlesonsilva** [comment]
Comecei a fazer mais ainda não terminei...

Arleson Silva
Fone: 85 98875 0089

IVIA ® Inovação e Tecnologia
CMMI + ISO 9001 + MPS.Br
WebSite: http://www.ivia.com.br<http://www.ivia.com.br/>
[IVIA]  [Mídias Sociais]        [Prêmios]

Em 25 de set de 2017, à(s) 20:44, jacksoncastro <notifications@github.com<mailto:notifications@github.com>> escreveu:


@arlesonsilva<https://github.com/arlesonsilva> conseguiu ver essa atividade?

**Comment by jacksoncastro** [comment]
Certo. Lembrando, a entrega é sábado dia 30/09

**Comment by arlesonsilva** [comment]
To esperto. Vou ver se consigo terminar algo hj!

Arleson Silva
Fone: 85 98875 0089

IVIA ® Inovação e Tecnologia
CMMI + ISO 9001 + MPS.Br
WebSite: http://www.ivia.com.br<http://www.ivia.com.br/>
[IVIA]  [Mídias Sociais]        [Prêmios]

Em 25 de set de 2017, à(s) 21:02, jacksoncastro <notifications@github.com<mailto:notifications@github.com>> escreveu:


Certo. Lembrando, a entrega é sábado dia 30/09
